<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder {
    public function run(): void {
        $products = [
            [
                'name' => 'Smartphone Galaxy S24',
                'description' => 'Smartphone Samsung Galaxy S24 com 128GB de armazenamento, câmera tripla de 50MP e tela AMOLED de 6.1 polegadas.',
                'price' => 2499.99,
                'stock' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Notebook Dell Inspiron',
                'description' => 'Notebook Dell Inspiron 15 com processador Intel Core i5, 8GB RAM, SSD 256GB e tela Full HD de 15.6 polegadas.',
                'price' => 3299.99,
                'stock' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fone de Ouvido Sony WH-1000XM5',
                'description' => 'Fone de ouvido wireless com cancelamento de ruído ativo, bateria de 30 horas e qualidade de áudio premium.',
                'price' => 1899.99,
                'stock' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smart TV LG 55 4K',
                'description' => 'Smart TV LG 55 polegadas 4K UHD com WebOS, HDR10 Pro e compatibilidade com Alexa e Google Assistant.',
                'price' => 2799.99,
                'stock' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mouse Gamer Logitech G Pro X',
                'description' => 'Mouse gamer sem fio com sensor HERO 25K, switches mecânicos e bateria de até 70 horas.',
                'price' => 599.99,
                'stock' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teclado Mecânico Corsair K95',
                'description' => 'Teclado mecânico RGB com switches Cherry MX, teclas macro programáveis e apoio para punho.',
                'price' => 899.99,
                'stock' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tablet iPad Air',
                'description' => 'iPad Air com chip M1, tela Liquid Retina de 10.9 polegadas, 64GB e compatibilidade com Apple Pencil.',
                'price' => 4199.99,
                'stock' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Câmera Canon EOS R6',
                'description' => 'Câmera mirrorless full-frame com sensor de 20.1MP, gravação 4K e estabilização de imagem de 5 eixos.',
                'price' => 12999.99,
                'stock' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smartwatch Apple Watch Series 9',
                'description' => 'Apple Watch com detecção de batimentos, ECG, oxímetro e integração com iOS.',
                'price' => 3899.99,
                'stock' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Console PlayStation 5',
                'description' => 'Console PS5 com SSD de 1TB, suporte a Ray Tracing e controles DualSense.',
                'price' => 4599.99,
                'stock' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Echo Dot 5ª Geração',
                'description' => 'Caixa de som inteligente com Alexa integrada e som aprimorado.',
                'price' => 399.99,
                'stock' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kindle Paperwhite 11ª Geração',
                'description' => 'Leitor digital com iluminação ajustável, tela de 6.8" e bateria de longa duração.',
                'price' => 649.99,
                'stock' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monitor LG UltraWide 29"',
                'description' => 'Monitor IPS Full HD com proporção 21:9, ideal para produtividade e multitarefas.',
                'price' => 1149.99,
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roteador TP-Link AX1800',
                'description' => 'Roteador Wi-Fi 6 com MU-MIMO, Beamforming e velocidades de até 1.8 Gbps.',
                'price' => 429.99,
                'stock' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HD Externo Seagate 2TB',
                'description' => 'HD portátil com conexão USB 3.0 e design compacto.',
                'price' => 469.99,
                'stock' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Webcam Logitech C920',
                'description' => 'Webcam Full HD com microfone estéreo e foco automático.',
                'price' => 499.99,
                'stock' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aspirador Robô Xiaomi Mi Robot',
                'description' => 'Aspirador inteligente com mapeamento por laser e controle via app.',
                'price' => 1899.99,
                'stock' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Impressora HP Ink Tank 416',
                'description' => 'Impressora multifuncional com tanque de tinta e conectividade Wi-Fi.',
                'price' => 829.99,
                'stock' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cadeira Gamer ThunderX3',
                'description' => 'Cadeira ergonômica com ajuste de altura, apoio lombar e acabamento em couro sintético.',
                'price' => 1099.99,
                'stock' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Placa de Vídeo RTX 4070',
                'description' => 'GPU NVIDIA com 12GB GDDR6X, Ray Tracing e DLSS 3 para alto desempenho em jogos.',
                'price' => 3999.99,
                'stock' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabinete NZXT H510',
                'description' => 'Gabinete mid tower com vidro temperado e excelente fluxo de ar.',
                'price' => 599.99,
                'stock' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fonte Corsair 750W 80 Plus Gold',
                'description' => 'Fonte modular com alta eficiência energética e baixo ruído.',
                'price' => 699.99,
                'stock' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Processador AMD Ryzen 7 5800X',
                'description' => 'Processador octa-core com clock de até 4.7GHz e arquitetura Zen 3.',
                'price' => 1699.99,
                'stock' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Memória RAM Kingston Fury 16GB',
                'description' => 'Módulo DDR4 3200MHz para alto desempenho em games e multitarefa.',
                'price' => 429.99,
                'stock' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SSD NVMe Samsung 1TB',
                'description' => 'Unidade de armazenamento ultrarrápida com leitura de até 3500MB/s.',
                'price' => 749.99,
                'stock' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cooler Master Hyper 212',
                'description' => 'Sistema de refrigeração a ar com ventoinha de 120mm para CPUs.',
                'price' => 239.99,
                'stock' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hub USB-C 7 em 1',
                'description' => 'Hub compacto com HDMI, USB 3.0, leitor de cartões SD e entrada de energia.',
                'price' => 199.99,
                'stock' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carregador Turbo Anker 30W',
                'description' => 'Carregador rápido com USB-C Power Delivery compatível com diversos dispositivos.',
                'price' => 149.99,
                'stock' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caixa de Som JBL Charge 5',
                'description' => 'Caixa de som portátil com Bluetooth, bateria de 20h e resistência à água.',
                'price' => 799.99,
                'stock' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
